// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package xdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadShredFilter returns the embedded CollectionSpec for shredFilter.
func loadShredFilter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ShredFilterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load shredFilter: %w", err)
	}

	return spec, err
}

// loadShredFilterObjects loads shredFilter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*shredFilterObjects
//	*shredFilterPrograms
//	*shredFilterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadShredFilterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadShredFilter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// shredFilterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type shredFilterSpecs struct {
	shredFilterProgramSpecs
	shredFilterMapSpecs
	shredFilterVariableSpecs
}

// shredFilterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type shredFilterProgramSpecs struct {
	XdpShredFilter *ebpf.ProgramSpec `ebpf:"xdp_shred_filter"`
}

// shredFilterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type shredFilterMapSpecs struct {
	TargetPort *ebpf.MapSpec `ebpf:"target_port"`
	XskMap     *ebpf.MapSpec `ebpf:"xsk_map"`
}

// shredFilterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type shredFilterVariableSpecs struct {
}

// shredFilterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadShredFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type shredFilterObjects struct {
	shredFilterPrograms
	shredFilterMaps
	shredFilterVariables
}

func (o *shredFilterObjects) Close() error {
	return _ShredFilterClose(
		&o.shredFilterPrograms,
		&o.shredFilterMaps,
	)
}

// shredFilterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadShredFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type shredFilterMaps struct {
	TargetPort *ebpf.Map `ebpf:"target_port"`
	XskMap     *ebpf.Map `ebpf:"xsk_map"`
}

func (m *shredFilterMaps) Close() error {
	return _ShredFilterClose(
		m.TargetPort,
		m.XskMap,
	)
}

// shredFilterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadShredFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type shredFilterVariables struct {
}

// shredFilterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadShredFilterObjects or ebpf.CollectionSpec.LoadAndAssign.
type shredFilterPrograms struct {
	XdpShredFilter *ebpf.Program `ebpf:"xdp_shred_filter"`
}

func (p *shredFilterPrograms) Close() error {
	return _ShredFilterClose(
		p.XdpShredFilter,
	)
}

func _ShredFilterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed shredfilter_bpfel.o
var _ShredFilterBytes []byte
